// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import net "github.com/stsiwo/chat-app/infra/net"
import user "github.com/stsiwo/chat-app/domain/user"

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// Id provides a mock function with given fields:
func (_m *IClient) Id() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Read provides a mock function with given fields:
func (_m *IClient) Read() {
	_m.Called()
}

// Receive provides a mock function with given fields:
func (_m *IClient) Receive() *net.Message {
	ret := _m.Called()

	var r0 *net.Message
	if rf, ok := ret.Get(0).(func() *net.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*net.Message)
		}
	}

	return r0
}

// Send provides a mock function with given fields: message
func (_m *IClient) Send(message *net.Message) {
	_m.Called(message)
}

// User provides a mock function with given fields:
func (_m *IClient) User() *user.User {
	ret := _m.Called()

	var r0 *user.User
	if rf, ok := ret.Get(0).(func() *user.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	return r0
}

// Write provides a mock function with given fields:
func (_m *IClient) Write() {
	_m.Called()
}
