// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"
import ws "github.com/gobwas/ws"

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

// ReadClientData provides a mock function with given fields: rw
func (_m *IHandler) ReadClientData(rw io.ReadWriter) ([]byte, ws.OpCode, error) {
	ret := _m.Called(rw)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(io.ReadWriter) []byte); ok {
		r0 = rf(rw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 ws.OpCode
	if rf, ok := ret.Get(1).(func(io.ReadWriter) ws.OpCode); ok {
		r1 = rf(rw)
	} else {
		r1 = ret.Get(1).(ws.OpCode)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(io.ReadWriter) error); ok {
		r2 = rf(rw)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// WriteServerMessage provides a mock function with given fields: w, op, p
func (_m *IHandler) WriteServerMessage(w io.Writer, op ws.OpCode, p []byte) error {
	ret := _m.Called(w, op, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, ws.OpCode, []byte) error); ok {
		r0 = rf(w, op, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
