// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import net "github.com/stsiwo/chat-app/infra/net"

// IPool is an autogenerated mock type for the IPool type
type IPool struct {
	mock.Mock
}

// Broadcast provides a mock function with given fields: message
func (_m *IPool) Broadcast(message *net.Message) {
	_m.Called(message)
}

// Find provides a mock function with given fields: key
func (_m *IPool) Find(key string) net.IClient {
	ret := _m.Called(key)

	var r0 net.IClient
	if rf, ok := ret.Get(0).(func(string) net.IClient); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.IClient)
		}
	}

	return r0
}

// Register provides a mock function with given fields: client
func (_m *IPool) Register(client net.IClient) {
	_m.Called(client)
}

// Run provides a mock function with given fields:
func (_m *IPool) Run() {
	_m.Called()
}

// Size provides a mock function with given fields:
func (_m *IPool) Size() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Unicast provides a mock function with given fields: message
func (_m *IPool) Unicast(message *net.Message) {
	_m.Called(message)
}

// Unregister provides a mock function with given fields: client
func (_m *IPool) Unregister(client net.IClient) {
	_m.Called(client)
}
