// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bufio "bufio"
import http "net/http"

import mock "github.com/stretchr/testify/mock"
import net "net"
import ws "github.com/gobwas/ws"

// IWsHandler is an autogenerated mock type for the IWsHandler type
type IWsHandler struct {
	mock.Mock
}

// UpgradeHTTP provides a mock function with given fields: r, w
func (_m *IWsHandler) UpgradeHTTP(r *http.Request, w http.ResponseWriter) (net.Conn, *bufio.ReadWriter, ws.Handshake, error) {
	ret := _m.Called(r, w)

	var r0 net.Conn
	if rf, ok := ret.Get(0).(func(*http.Request, http.ResponseWriter) net.Conn); ok {
		r0 = rf(r, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	var r1 *bufio.ReadWriter
	if rf, ok := ret.Get(1).(func(*http.Request, http.ResponseWriter) *bufio.ReadWriter); ok {
		r1 = rf(r, w)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bufio.ReadWriter)
		}
	}

	var r2 ws.Handshake
	if rf, ok := ret.Get(2).(func(*http.Request, http.ResponseWriter) ws.Handshake); ok {
		r2 = rf(r, w)
	} else {
		r2 = ret.Get(2).(ws.Handshake)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(*http.Request, http.ResponseWriter) error); ok {
		r3 = rf(r, w)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}
